# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3775816324c01a2349dc6072ecd1851cf70e88a5ae8611919f04bad513b6e8fd857d22320eaa190f2fbd4743b144e3fd4d6b188322b573e63b285cd8eeec6b43

test:
  secret_key_base: af96fa9ba2fc165bbd6d279d7c41d76a99f7d162e0366330dd0259a49ea6983bc2a8f300032a64d909edc328dd7bae9211a5d25a17622d0aebf6243347832cef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
